language: python
python:
  - "3.6"

services:
  -docker


before_script: pip install docker-compose

#script it runs before running automation commands

script:
- docker-compose run app sh -c "python manage.py test && flake8"