#travis runs python server, runnig 3.6, makes docker service avaliable, and runs script
language: python
python:
  - "3.6"

services:
  -docker

#script it runs before running automation commands
before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test"