# Generated by Django 2.1.7 on 2019-03-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='time_minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
